### ISSUE TITLE
question: can OM automate PCF on GCP process

### ISSUE THREAD

**Issue by sidd-harth** [pivotal-cf/om#124]
I am trying to understand how installation of PCF on GCP can be done by Terraforming-GCP. After going through available documentation. I understood it involves 4 steps,

1. Prepare GCP env,
2. Install Ops Manager,
3. Install Bosh Director,
4. Install Elastic Runtime

As far as i understand using Terraform scripts we can automate,

1. Prepare GCP env
2. Install Ops Manager

I was searching for APIs for Elastic Runtime? To create any kind of automated scripts for Elastic Runtime installation. I searched in Pivotal docs & couldn't find them. 

So using OM CLI can we automate interactions with ops manager to do steps 3/4? Any help is appreciated.

**Comment by davewalter** [comment]
Hi @sidd-harth.

The `om` CLI is a client for the Ops Manager API, so you can definitely use it to automate interacting with an Ops Manager to configure and install the BOSH director and any product tiles you want. However, it does not interact with other services (such as Pivotal Network), and it does not know anything about a specific product (such as the ERT), so you will have to provide your own configuration files. We do not currently provide scripts for this due to the burden that supporting them would place on the team. You can look at the [pcf-pipelines](https://github.com/pivotal-cf/pcf-pipelines) repo for tooling that uses `om`. You could also reach out to the Master Pipeline and/or Customer 0 teams to see if they support anything that you could use.

Please let us know if you have any specific questions about `om`.

Regards,
Dave

**Comment by utako** [comment]
Hi @sidd-harth,

I'm going to go ahead and mark this as resolved. Please feel free to reopen this issue with any more questions you might have about `om`, and we'll be happy to help you out.

Thanks,
@utako, PCF Releng Team
