### ISSUE TITLE
Add "selective deploy" functionality for PCF >2.1

### ISSUE THREAD

**Issue by bmhkb4** [pivotal-cf/om#141]
Add "selective deploy" functionality for PCF >2.1.

This is new coming down the pipe with 2.1 and would make om-linux and the pipelines that call in a lot cleaner and faster.

![image](https://user-images.githubusercontent.com/3407663/38686397-ce157d56-3e39-11e8-9dc8-021a73228925.png)

**Comment by jtarchie** [comment]
You can use `om curl` to do this. Do you have a proposed interface for this? This being a single command would still require this large JSON payload.

**Comment by aegershman** [comment]
I hope you'll forgive the semi-spammy "micro-blogging" style of this post. [But I've been doing some experimentation to implement an upgrade-tiles pipeline using selective deploy](https://github.com/aegershman/pcf-pipelines-selective-deploy). I've got a minimal PoC of using om-linux to do selective deploys. I figured I'd share some things:

1. You can use om-linux curl like this:
```
om-linux --target "https://${OPSMAN_DOMAIN_OR_IP_ADDRESS}" \
	--skip-ssl-validation \
	--client-id "${OPSMAN_CLIENT_ID}" \
	--client-secret "${OPSMAN_CLIENT_SECRET}" \
	--username "${OPSMAN_USERNAME}" \
	--password "${OPSMAN_PASSWORD}" \
	curl \
	--path /api/v0/installations \
	--request POST \
	--data '{"deploy_products": ["p-healthwatch-jsldfkj93jlsdfj"]}'
``` 

But [using this method to trigger selective-deploy is clunky because you still have to build the `--data` payload containing the product GUIDs you want to selectively deploy on.](https://github.com/aegershman/pcf-pipelines-selective-deploy/blob/master/tasks/selective-deploy/task.sh#L22-L26), which requires some crusty-looking `jq` logic to match a `product_name` against it's staged `product_guid`.

2. Once you perform the `selective_deploy` using curl, if everything works properly, you're returned an installation id & the 'curl' session ends. It looks like this:
```json
{
  "install": {
    "id": 64
  }
}
```

With this id, you don't know whether or not the installation actually succeeds-- you only know that it successfully started. So now we'll need to "listen" to the logs coming from that install id. You'd probably want to include logic to capture the returned ID and listen to the logs. You could do this by polling the `installations/:id` endpoint every couple seconds or so, [which I think is what om-linux is doing when it performs apply-changes](https://github.com/pivotal-cf/om/blob/master/commands/apply_changes.go#L68-L91). I still haven't written a great way to do this, though. So at the moment, in the example I linked, you don't get any logs.

My current solution isn't great or particularly robust; hopefully this helps someone else to come up with a better way.

**Comment by davewalter** [comment]
Hi @aegershman. I definitely think that we will be adding support for this as soon as team bandwidth allows. Until such time as `om` supports this natively, you could actually trigger the selective deploy as you suggested and then use `om apply-changes` to "attach" to the running deployment and stream the logs. This is an undocumented feature of the `apply-changes` command.

Hope that helps.

**Comment by mcwumbly** [comment]
>  I definitely think that we will be adding support for this as soon as team bandwidth allows.

Unfortunately, team bandwidth has not allowed!

I'm adding a `pr-welcome` label to this, though I think the spec still needs some more clarity, so if anyone is interested in this feature, let's start there.

One thing to consider is that we're moving towards preferring the `--config` flag in `configure-product` now vs. the separate flags for `--product-network`, `--product-properties`, and `--product-resources`.  We are likely to deprecate these latter flags in the near future.

So the design of this feature should anticipate that.
