### ISSUE TITLE
specify target and authorization flags via a config file

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#153]
right now if we want to target the om to use specific commands, we need to provide `--target`, `--username`, `--password`, and `--skip-ssl-validation` flags each time. This became a problem when we were trying to externalize the configurations in a Concourse task. It would be nice to have a config file for target and authentication credentials so that we can pass a single config file each time instead of the same params.

And we are willing to make a PR for this issue.

**Comment by ryanmoran** [comment]
What do you feel the advantage of a file would be over supporting environment variables for flags? Do you explicitly want your credentials written to disk?

**Comment by fredwangwang** [comment]
Yes, we want to have a versioned control of the configurations for different foundations. It would quickly become unmanageable if we are passing in the variables by flag or env variables. So having a config file stored somewhere (like s3 bucket) provides us a central and versioned configuration we could rely on.

**Comment by zachgersh** [comment]
There are quite a few ways that I could envision doing this that do not involve writing the credentials down to disk. `om` is trying to make sure you do what is the "secure" thing instead of leaving your credentials around in various files.

One such solution would be to have a file with a bunch of export statements in it that set your credentials once sourced.

**Comment by mcwumbly** [comment]
closing per: https://github.com/pivotal-cf/om/pull/154#issuecomment-387874050
