### ISSUE TITLE
Consider enhancement for experimental config-template command

### ISSUE THREAD

**Issue by calebwashburn** [pivotal-cf/om#191]
Similar to config-template a solution has been created outside of `om` to generate a complete template of configuration options not just product-properties.  This also generates `ops-files` for each selector and optional property within product properties.  Also to expand the `azs` that a given tile deployment targets.  Wanted to gauge interest in having this submitted as a PR to enhance `config-template` command.

https://github.com/pivotalservices/tile-config-generator

This would also require extending `configure-product` to also take in ops-file(s) as an argument to complete the interpolation capability recently added.

**Comment by calebwashburn** [comment]
@mcwumbly Just resurfacing this to see if this kind of feature is something that `om` would consider as either a different command or to replace `config-template` command or if this is something that should remain external as have gotten good feedback on approach with https://github.com/pivotalservices/tile-config-generator.  This does require that PR https://github.com/pivotal-cf/om/pull/197 be merged as tile-config-generator does depend on both vars and ops-files for interpolation.

**Comment by mcwumbly** [comment]
hey @calebwashburn, I think `config-template` definitely needs some improvement, in particular around how it handles selectors right now - but it's not something we have thought about too deeply.  

a few folks on our team have been on vacation and we've got a fair bit of other stuff going on, so I'm sorry we haven't been able to give your PR's the attention they deserve.

I'm also interested to here what other recent contributors like @jtarchie think about this feature, or whether there are aspects of it that we could start with.

**Comment by jtarchie** [comment]
@mcwumbly, recently, we talked to client that was using this tool.

The [tile config generator](https://github.com/pivotalservices/tile-config-generator) provides full functionality for configuring a tile beyond properties. It supports generating configs for resources, properties, and errands.

The generator separates responsibility of required values and optional values.

For example:

* if a property is required
   * and has a default value, that values is put into a `default-vars.yml`
   * and has no default value, the `interpolation` step will error on missing the value
* if a property is optional
   * and has a default value, that values is put into a `default-vars.yml`
   * and has no default value, the `interpolation` step will not error

The above describe single key-value pairs. When it comes to collections and selectors, because they represent groups of values, is separated into ops-files. To "select" a value, you add an ops file, which sets the `select_value`, and expose other properties (via vars) you can set. Those vars follow the same logic for defaults and required as above.

The client expressed the useful of this pattern.

* it fails fast. The interpolation of vars and ops files tells the user what they are missing before it uploads to OpsMan.
* it exposes new required properties before having to upload the tile to OpsMan
* it was very useful for new tiles, so they didn't have to staged and then `stage-config` down
* it allowed picking and choosing for feature via ops files

Seeing how the client use the tool really showed how useful a full solution like tile-config-generator can be.

**Comment by mcwumbly** [comment]
@jtarchie thanks for looping back around with the feedback.  I think this feature is more useful to the users that your team is focused on, so I'm happy to defer to you all about the best way forward here. Also, the `config-template` command is marked `**EXPERIMENTAL**` intentionally to allow us to navigate this design space with the expectation that it is not yet stable.

If y'all feel like @calebwashburn 's proposal is concrete enough to move forward with at this point, I think you could run with it and/or open separate issues for smaller features you'd like to work on along the way in that direction.

/cc @nbconklin

**Comment by kcboyle** [comment]
closing this issue as proposal https://github.com/pivotal-cf/om/issues/324 addresses this in more detail
