### ISSUE TITLE
`staged-director-config` should heuristically parameterize credentials

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#192]
The `staged-config` command includes a flag (`--include-placeholders`), which will bosh parameterize anything that is a credential.

There should be support for this with `staged-director-config`.
The heuristic portion comes into play because director properties don't have __types__ like the tile properties do.
The parameters would be determined if the property key contains any of the following in its name `"password", "user", "cert", "key"`.

The reason for this behaviour is to help separate the concern of credentials from config files. The exported config, from `staged-director-config`, can be reusable across OpsManager foundations.

We currently have a working example. We'd like to add this functionality to `om` directly.

**Comment by anEXPer** [comment]
We've blocked work to do this on alignment about the feature, and are coming up on it in our backlog. @mcwumbly do y'all have feelings on this?

**Comment by mcwumbly** [comment]
> @mcwumbly do y'all have feelings on this?

Hmm... sorry, I haven't given it much thought yet.  Looking now, it sounds a bit tricky to me, but:

> We currently have a working example. We'd like to add this functionality to om directly.

Can you point to the working example and/or illustrate here inline what the current and future behavior is that you have in mind more concretely?

For example:

current output :
```
some:
  yaml: stuff
```

future output:
```
some:
  other: stuff
```

**Comment by fredwangwang** [comment]
Here is an example of the diff dumped from a vsphere opsman.

```diff
-  bosh_disk_path: "some-path",
-  bosh_template_folder: "some_templates",
-  bosh_vm_folder: "some_vms",
-  datacenter: "one-dc",
-  ephemeral_datastores_string: "some-datastore",
-  nsx_networking_enabled: false,
-  persistent_datastores_string: "some-other-datastore",
-  ssl_verification_enabled: false,
-  vcenter_host: "some.vcenter.host",
-  vcenter_username: "user@name.com",
+  bosh_disk_path: "((iaas-configuration_bosh_disk_path))",
+  bosh_template_folder: "((iaas-configuration_bosh_template_folder))",
+  bosh_vm_folder: "((iaas-configuration_bosh_vm_folder))",
+  datacenter: "((iaas-configuration_datacenter))",
+  ephemeral_datastores_string: "((iaas-configuration_ephemeral_datastores_string))",
+  nsx_address: "((iaas-configuration_nsx_address))",
+  nsx_ca_certificate: "((iaas-configuration_nsx_ca_certificate))",
+  nsx_mode: "((iaas-configuration_nsx_mode))",
+  nsx_networking_enabled: "((iaas-configuration_nsx_networking_enabled))",
+  nsx_password: "((iaas-configuration_nsx_password))",
+  nsx_username: "((iaas-configuration_nsx_username))",
+  persistent_datastores_string: "((iaas-configuration_persistent_datastores_string))",
+  ssl_verification_enabled: "((iaas-configuration_ssl_verification_enabled))",
+  vcenter_host: "((iaas-configuration_vcenter_host))",
+  vcenter_password: "((iaas-configuration_vcenter_password))",
+  vcenter_username: "((iaas-configuration_vcenter_username))",
-  trusted_certificates: nil,
+  trusted_certificates: "((security-configuration_trusted_certificates))",
```

Basically we replace the entire `iaas-configuration` section to be the placeholder in the format of `"${top_level_key_name}" + "_" + "${field_name}"`, and then heuristically go through the rest sections to replace the value of the keys which contain "password" or "user" or "cert" or "key" to the placeholder. 

The `trusted_certificates` in `security-configuration` section is an example (the last line in diff), it contains keyword `cert`, so we replace the value of it to be the placeholder `security-configuration_trusted-certificates`

**Comment by mcwumbly** [comment]
> We view one of the major utilities of placeholders as allowing the use of the same base config across several environments, and IaaS configuration is as environment-coupled as creds, or more so.

Yeah, I think this makes sense. If that's the case, is the distinction between the two useful at all? (That is to say, do we really need the prefixes `iaas-configuration_` and/or `security-configuration_`?)

Is there anything in the output of `staged-director-config` that _shouldn't_  be a placeholder?

From the OP (@jtarchie): 
> The heuristic portion comes into play because director properties don't have **types** like the tile properties do.

I'm not sure I'm seeing any type distinction in the diff that was posted by @fredwangwang. What am I missing?

Happy to hop on a call if it's easier to explain in real time.

**Comment by mcwumbly** [comment]
is the first command `om staged-director-config` and the second one `om staged-director-config --include-placeholders`?

**Comment by fredwangwang** [comment]
yes

**Comment by mcwumbly** [comment]
OK, I think I'm catching up to you now.

I'm tempted to push for the following for consistency with our UX for product configuration commands:

- `om staged-director-config` should exclude the keys for `trusted_certificates` and the `iaas-configuration` map by default
- `om staged-director-config --include-credentials` should include the _values_ for the above
- `om staged-director-config --include-placeholders` should include placeholders, as spec'd here.

Does the above make sense to you? 

(We don't have to do it all at once, just checking if we're in alignment on potential future features to make this all consistent)

**Comment by fredwangwang** [comment]
I agree we should keep the user interface and the expected result of `staged*-config` commands as similar as possible. Here are the cases you mentioned:

> om staged-director-config should exclude the keys for trusted_certificates and the iaas-configuration map by default 
& 
om staged-director-config --include-placeholders should include placeholders, as spec'd here.

I think it is fine, except do we want to exclude `security-configuration.trusted_certificates`? Because technically it is not a cred, it is a certificate. The reason `--include-placeholder` parameterize the field is because it is potentially _env specific_. 

> om staged-director-config --include-credentials should include the values for the above

I don't think we can do this. For `staged-config` it is doable because we can get all the credentials from api `/api/v0/deployed/products/%s/credentials/%s`. It is not the case for the **director**. There is no api endpoint (as far as I can tell) we can use to get the obscured iaas-configuration properties (`auth_json` for gcp for example)

----

Thinking more about this, it becomes kinda interesting to consider from the code perspective...

 Since originally these two commands are so thin on top of the api endpoint, all they do are getting the api payload and printing to the screen. As we decide more about changing the default behaviors of the commands, we essentially deviate from the original behavior. Although we now agree on the changes to be made to the default behavior, is there a risk that breaking some use cases which depend on the original default behavior?

I am kinda inclined towards restoring the default behavior, but making another flag like `--filter-extraneous` or `--exclude-credential` or anything, to remove the credential types from the payload.

----

Anyway, from the implementation standpoint, I think no matter what we eventually decide, `staged-director-config --include-credential` is not doable, all others are pretty easy.

**Comment by mcwumbly** [comment]
I reordered the keys in your example above so I could diff them more easily, and this is what I see:

```bash
$ diff no-args.yml include-placeholders.yml
```

```diff
37,40c37,38
<   associated_service_account: account-name
<   guid: 349affc11fb0fce37be6
<   name: default   # internal name that opsman uses, not configurable
<   project: project
---
>   associated_service_account: ((iaas-configuration_associated_service_account))
>   project: ((iaas-configuration_project))
98c96
<   trusted_certificates: null
---
>   trusted_certificates: ((security-configuration_trusted_certificates))
```

I'm suggesting that instead, the new behavior should be:

```bash
om staged-director-config > no-args.yml
om staged-director-config --include-placeholders > include-placeholders.yml
om staged-director-config --include-credentials > include-credentials.yml
```

```bash
diff no-args.yml include-credentials.yml
```

```diff
35a36,40
> iaas-configuration:
>   associated_service_account: account-name
>   guid: 349affc11fb0fce37be6
>   name: default   # internal name that opsman uses, not configurable
>   project: project
92a98
>   trusted_certificates: null
```

```bash
diff no-args.yml include-placeholders.yml
```

```diff
$ diff no-args.yml include-placeholders.yml
35a36,38
> iaas-configuration:
>   associated_service_account: ((iaas-configuration_associated_service_account))
>   project: ((iaas-configuration_project))
92a96
>   trusted_certificates: ((security-configuration_trusted_certificates))
```

```bash
diff include-credentials.yml include-placeholders.yml
```

```diff
$ diff include-credentials.yml include-placeholders.yml
37,40c37,38
<   associated_service_account: account-name
<   guid: 349affc11fb0fce37be6
<   name: default   # internal name that opsman uses, not configurable
<   project: project
---
>   associated_service_account: ((iaas-configuration_associated_service_account))
>   project: ((iaas-configuration_project))
98c96
<   trusted_certificates: null
---
>   trusted_certificates: ((security-configuration_trusted_certificates))
```

----

Does that make sense?

[examples.zip](https://github.com/pivotal-cf/om/files/2226124/examples.zip)

**Comment by kcboyle** [comment]
Thanks for the detailed examples (we're still finishing up) 

One final question comes around what to do with the params OpsManager doesn't return (as you cannot just take the config from `staged-director-config` and pass it directly to a clean install using `configure-director` due to the params that OpsManager filters out)

Our strong assumption (the one we made as a non-cross-collaborated team) is that it is OK that we do not return these parameters, because OpsManager does not return them. If we wanted to return them, `om` would have to have knowledge of the internal parameter workings of OpsMan, which, given `om`'s history in separating itself from any and all OpsManager config knowledge, seems to work against `om`'s goals. 

Put another way, given the movement away from OpsMan config (`configure-bosh` -> `configure-director`), we presume that `om` would _not_ want/need these missing fields from the `staged-director-config` step because that would couple `om` to versions of OpsManager again. 

Is this a fair asusmption @mcwumbly ?

**Comment by mcwumbly** [comment]
@kcboyle I think you're probably correct, but I'm not sure I'm completely following.   Perhaps you could help illustrate by 

> what to do with the params OpsManager doesn't return (as you cannot just take the config from `staged-director-config` and pass it directly to a clean install using `configure-director` due to the params that OpsManager filters out)

If I'm following, you're saying the current workflow has this step 2 below:

1. `om staged-director-config > some-config.yml`
2. `# make these changes to some-config.yml`
3. `om -t https://some-other-director/ configure-director -c some-config.yml`

To help be better understand, what does step 2 currently entail?

**Comment by mcwumbly** [comment]
I see. Yuck.

> If we wanted to include vcenter_password, for example, we'd have to have some sort of map **(which is what we do in platform-automation now)** that includes certain properties for certain IaaSs on potetentially different versions of OpsMan (if params changed)

It bothers me that you have to do this elsewhere.  

Ideally, we'd get this back from Ops Manager. This feels like something we request from them, and potentially have backported.  In the mean time, I'm not sure what the bet thing to do is.  I can see it both ways.

If you're going to maintain this map _anyway_, I'm not sure it matters whether that code lives in `om` or some wrapper.  There may be a case to bring it into `om`.  But this sounds like a good time to open another issue to discuss this.

**Comment by kcboyle** [comment]
Ideally, yes. The backport would have to go back pretty far if we want to support the minimum supported version we can, and I don't know if they have the bandwidth to do that work but we can open a conversation with the OpsManager team and see what they might be able to do.

We'll open up a new issue for the iaas-configuration map issues. In the meantime, we submitted a PR addressing this one.

**Comment by jtarchie** [comment]
@mcwumbly: We are closing this since our initial PR has been merged. We will close and open other issues if there needs to be more work done.
