### ISSUE TITLE
"Secondary" ready-only user for opsmgr on apply-changes

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#248]
As a PCF operator, I use Concourse to manage opsmgr changes. `Apply-changes` can take quite some time. Because the logged-in opsmgr Concourse bot user must have admin privileges to trigger the `apply-changes`, and because only one admin can be logged in at once, if anyone logs in to the opsmgr while Concourse is performing `apply-changes`, the job will fail.

Therefore, I'm imagining a "secondary" read-only user which can listen to the `apply-changes` log stream after the `apply-changes` has been kicked-off. The "primary" admin user would start the `apply-changes`, logout, then the "secondary" read-only user could log in and re-attach to the logs. This would allow other operators to log into opsmgr while Concourse is running.

**Comment by ljfranklin** [comment]
@aegershman interesting, didn't know that OpsMgr only allowed one logged in Admin user. Rather than passing the `apply-changes` command multiple users, I wonder if invoking multiple commands with different users is a bit cleaner. We already have `om installation-log --id SOME_ID` which could be passed a read-only user. Maybe `om` could add an `om apply-changes --no-tail` or similar which returns only the installation log ID to STDOUT, you could then pass that ID to `om installation-log --id ID`. This avoids implementation complexity around juggling multiple users in the code and might result in a more composable design for `om` overall. Would this meet your use case?

**Comment by aegershman** [comment]
Hm. I'm pretty sure only one admin can be logged in at once & multiple "read-only" users could be logged in as well, but could be completely wrong...? From the opsmgr 2.2.4 doc under `sessions`:

```
Only one user can be active in PCF Ops Manager at a time. For API users, we consider a user to be active during the period between their last request and when their token expires. 
```

<img width="543" alt="screen shot 2018-09-05 at 8 39 46 pm" src="https://user-images.githubusercontent.com/5619476/45129894-e6582500-b14b-11e8-80a5-0437059dd76b.png">

Actually, to be entirely honest, the more I think about this, I don't have a super compelling use case to justify the complexity this requires. We can close this unless you'd like to leave it open for discussion.

**Comment by jtarchie** [comment]
It is not clear to me how to _log out the admin_ after hitting apply changes. The fact that `om` logs in everytime speaks more to the user flow @ljfranklin described.

**Comment by aegershman** [comment]
I don't think I've done quite enough research/testing/validation into this on my own to justify an actual use-case. I'll close this. Thanks for your time and consideration.
