### ISSUE TITLE
allow import-installation to take a config file

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#251]
Story to unwrap import-installation

Currently, we have a wrapper around import-installation to allow the configurations to be passed in using --config config.yml. Would like to merge that behavior into om.

Proposed changes:
adding a --config flag which takes configuration file for auth.

File format: replicate flat flag structure

Intended behavior:
`--decryption-passphrase` will always set the decryption passphrase
`--polling-interval` will always set the polling interval

configFile.yml:
```
decryption-passphrase: ((decryption-passphrase))
polling-interval: ((polling-interval))
```
will set the product name if the flag is not set

**Comment by ljfranklin** [comment]
@kcboyle I'm a little confused by your description. To match the format of the other issues y'all opened, I'd expect this feature would allow you to specify `import-installation --config config.yml` as an alternative to the following flags:
- `decryption-passphrase`
- `installation`
- `polling-interval`

The config file would look something like this (your example had placeholders which I'm not sure was intentional):

```yaml
decryption-passphrase: some-password
polling-interval: 10
installation: ./some/path/on/disk
```

If the above flags were omitted the values for those properties would be read from the config file. If either the decryption passphrase or installation path was not passed as a flag or in the config file, `om` would raise an error.

Does that sound correct?

**Comment by jtarchie** [comment]
That is correct. We missed it when writing it.

@ljfranklin: We have a [proposal](https://github.com/pivotal-cf/jhanda/issues/9) for `jhanda` that might make all these config file issues easier to do.

**Comment by mcwumbly** [comment]
> We have a proposal for jhanda that might make all these config file issues easier to do.

I don't have a good feel for whether this belongs in here, or if it'll take some time to gain alignment on the design. 

But **if** it's feeling like it's going to take time to hash out the design or decide, one option in the short term may be to first wrap jhanda in`om` to add this behavior for now.  That could solve the `om` problem of centralizing this responsibility and then offer a reference implementation to consider pushing down into `jhanda`.

**Comment by jtarchie** [comment]
Delivered!

```
om import-installation -h

....
Command Arguments:
  --config, -c                  string             path to yml file for configuration (keys must match the following command line flags)
  --decryption-passphrase, -dp  string (required)  passphrase for Ops Manager to decrypt the installation
  --installation, -i            string (required)  path to installation.
  --polling-interval, -pi       int                interval (in seconds) at which to print status (default: 1)

```
