### ISSUE TITLE
Providing extra fields in an env file tries to translate all values to flags

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#258]
command: 
```
om --env config.yml configure-authentication --config config.yml
could not execute "configure-authentication": could not parse configure-authentication flags: flag provided but not defined: -target
```

our config.yml has the following properties 
```
target: 
skip-ssl-validation:
username: 
password:
decryption-passphrase:
```

Use case:
Since `configure-authentication` shares `username` & `password` fields in the `env file`, we want to just provide one file that can be used in both places. But since `env file` contains `target` and `skip-ssl-validation`, which are not recognized by `configure-authentication, it triggers the above error.

Proposal:
Ignore any unknown fields in the config file.
affected commands:
`configure-authentication` & `configure-saml-authentication` & `import-installation`

**Comment by ljfranklin** [comment]
Classic UX question, do you error on unknown fields or not? As you're describing allowing unknown fields allows you to simplify things in CI. Also sometimes makes upgrades easier as a single config file can be used in both old and new envs as long as you can add new keys which the old env ignores. However, I've been bitten countless times by typoing a property or nested under the wrong key in BOSH only to see my deploy error 20 minutes later. If BOSH would have yelled at me immediately that it didn't understand a given key I would have been so much happier.

Given the UX gotchas with not validating unknown flags, I'd be in favor of keeping the existing validation. Your CI tasks now have to create two files instead of one, but this seems like a minor implementation detail of your CI task that the consumers of that task probably won't notice. Also feels like there's some clarity in having a single `env.yml` that all tasks consume and each task creates a second file containing values relevant to that task.

**Comment by ljfranklin** [comment]
A more specific example, you run `configure-product` with a config file containing the key `product_network` which you accidentally gave an underscore rather than a hyphen. Instead of failing with "unknown key", your CI task goes green but silently fails to configure the network. You now get even more confusing errors as your next CI job fails due to the tile not being fully configured.

**Comment by fredwangwang** [comment]
> If BOSH would have yelled at me immediately that it didn't understand a given key I would have been so much happier.

That's true, as we talked about the potential solution, we realized that the error message is actually a valid one, fixing this 'bug' feels like a hack 😞. So we wanted to open up an issue to discuss with you guys first before we brute forced it to make it work.

An alternative might be to go through some effort and ignore flags from the env file, but, again, might be more of a hack(or at the very least it's unclean) than a good solution.

**Comment by fredwangwang** [comment]
Something to note and/or fix: 
the `--env` flag is handled by the yaml unmarshal (not jhanda like the above issue)

the behavior for `--env` does actually ignore unknown fields. If we'd like to keep the experiences the same, should we enforce this same behavior?

**Comment by ljfranklin** [comment]
> the behavior for `--env` does actually ignore unknown fields

Having `--env` using the same parsing logic as all the nested commands seems like a good thing to do.

**Comment by jtarchie** [comment]
After discussing with @ljfranklin, we are going to try and consolidate the config logic between `--env`, `--config`, and `--config` on product/director.

**Comment by kcboyle** [comment]
This behavior is not yet fixed. For example, env.yml:
```
target: "example.com"
skip-ssl-validation: true
username: username
password: password
decryption-passphrase: passphrase
bogus: not-real
```

run with the command: 
```
○ →om --env env.yml staged-config --product-name cf
product-name: cf
product-properties:
  .cloud_controller.allow_app_ssh_access:
    value: true
```

**Comment by kcboyle** [comment]
This will be released in the next version of `om` (Currently: 1.0.1. Potentially 1.1.0 depending on if new features are added)
