### ISSUE TITLE
PROPOSAL: replacing `config-template` with tile config generator

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#324]
# Problem

The command `config-template` generates a config file based on the metadata in a tile. This does not require a running OpsMan, like `staged-config`.

`configure-template` doesn't work well for some tiles.

# Proposed Change

The tool [tile config generator](https://github.com/pivotalservices/tile-config-generator) has been a widely used replacement for `configure-template`.

The current command [`tile-config-generator generate`](https://github.com/pivotalservices/tile-config-generator#generate) generates a variety of YAML files. They can be combine together (using `om|bosh interpolate`) to have a final configuration file for a product.

The tool breaks down a tile configuration with ops-file and vars-file by the following:

* a parameterized file representing required properties that can be interpolated using tools like bosh interpolation
* a resource config yaml variable file with defaults
* a properties config yaml variable file with default for required properties
for each selector in the tile a yaml operations file that allows toggling the selector to alternative values in the features directory
* for each optional property in the tile a yaml operations file that allows setting optional properties in the optional directory

We'd like to pull. It is feature complete and battle tested by many users.

# Notes
* This issue will be updated as we learn more about pulling in the source.

Please comment on the issue with concerns and thoughts.

/cc: @calebwashburn

**Comment by zachgersh** [comment]
My question would be, why (and this isn't trying to be a snarky why its has good intentions I promise).

What are the clear benefits of adding more code to `om` when the tools already look like they can and do work well together now?

**Comment by jtarchie** [comment]
The goals would be:

1. Code ownership. This project is originally made by @calebwashburn. It is used heavily in the field. We'd be taking it over to maintain it.
2. One less CLI for customers to hunt down. I don't think we are worried about adding more code; it seems like the arbitrary metric. `om` helps with a platform operators usage workflows, which includes both product tiles and OpsManager.

The user case of piping one output into another just is impossible. Tile config management still requires a lot of user involvement. It has to be `generate-tile-config | <user edits some YAML files> | om configure-product`.

**Comment by zachgersh** [comment]
@jtarchie nice goals, but I think only 2 seems like a reason to pull it into the code base (at the expense of making `om` now more complex to change). 

I also don't think my metric was ever just "add more code" and that was too simple of a way for me to say that, if the code bases are separate their concerns are separate and they can evolve independently. That separation of concerns is nice.

1. own the code, just keep it separate.
2. are customers hunting this down or is the field using it and they know how to find it?

Finally, shouldn't you be be optimizing for the `<user edits some YAML files>` so that what is impossible actually becomes possible? Feels like a better spot to devote your energy than merging the code bases together. 

I could see it your way if they are so tightly coupled (maybe they are) that no one would ever need to do anything with `generate-tile-config` beyond using it with `om`. If that's the case, merge away.

**Comment by mcwumbly** [comment]
> I could see it your way if they are so tightly coupled (maybe they are) that no one would ever need to do anything with `generate-tile-config` beyond using it with `om`. If that's the case, merge away.

I think that is the case here. 

We already build similar features into `om`, but hadn't taken it quite as far as what `tile-config-generator` does. 

More generally, I think this general problem is worth keeping in mind as we consider the designs for any next generation release-authoring features. How can releases describe what their configuration requirements are well enough so that as much as possible, configuration can be validated independently by the release artifact, independently of the software that actually deploys it?

But given the current constraints of Ops Manager, the tile DSL, etc, this seems like a reasonable way to get a tile to tell you what it needs to be configured.

**Comment by kcboyle** [comment]
https://github.com/pivotal-cf/om/issues/191 is a similar proposal

**Comment by clhynfield** [comment]
Having worked with a lot of clients developing tile configuration automation, this proposal sounds _really_ attractive, for a lot of the reasons @jtarchie’s user research revealed over in #191, mostly centering around tightening the platform developer feedback loop and making development easier and faster: 

> * it fails fast. The interpolation of vars and ops files tells the user what they are missing before it uploads to OpsMan.
> * it exposes new required properties before having to upload the tile to OpsMan
> * it was very useful for new tiles, so they didn't have to staged and then `stage-config` down

Very many of our new clients are overwhelmed with the barrage of new tooling we expect them to become instant experts on. One Ops Manager server, one client configuration tool sounds more humane, user-centric to me.

**Comment by jtarchie** [comment]
This has been pulled into `config-template` and released as a of https://github.com/pivotal-cf/om/releases/tag/0.55.0.

We have marked the feature as EXPERIMENTAL, because there is the possibility of minor changes to better fit with the conventions of `om`. This is a first pass. We'd like feedback. Open new issues has they happen.
