### ISSUE TITLE
Enhancements to apply-changes to make a more robust selective deploy

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#325]
`apply-changes` will reattach to an already running apply changes on a given director if run more than once(to prevent failure if there's an accidental disconnect from `om`). 

When using a selective deploy (--product-name), this will always still reattach to a running apply changes, and return failure or success. However, a selective deploy will not differentiate if the already running apply changes is for the selective deploy given or if it is just some other apply changes. 

The Ops Manager API returns the following when hitting the `/api/v0/installations` endpoint:
```
{
  installations: [
    {
      user_name: "administrator@vsphere.local",
      finished_at: null,
      started_at: "2019-02-20T16:56:41.829Z",
      status: "running",
      additions: [ ],
      deletions: [ ],
      updates: [ ],
      unchanged: [
        {
          identifier: "cf",
          label: "Pivotal Application Service",
          product_version: "2.4.3",
          deployment_status: "pending",
          change_type: "unchanged",
          guid: "cf-randomsha"
        },
        {
          identifier: "p-bosh",
          label: "BOSH Director",
          product_version: "2.4-build.152",
          deployment_status: "running",
          change_type: "unchanged",
          guid: "p-bosh-randomsha"
        }
      ],
      id: 20
    },
  ]
}
```

If we could intelligently have selective deployments check the status of a `"running"` installation, and validate the `unchanged` or `changed` products match what you are trying to selectively deploy, that would make the feature more robust. right now, it is very misleading, and could lead to a false success of the selective deploy, even if it wasn't the current deploy running. 

Expected Behavior:
if using selective deploy and the product defined is not the product(s) currently being deployed
I want to return a failure to maintain honestly of the command.

**Comment by jtarchie** [comment]
After some discussion, we've actually chosen to make the re-attachment to an `apply-changes` optional by the user.

If a user runs `apply-changes` from the CLI (#1), makes changes, and runs `apply-changes` again (#2).

* If #1 is still running, the #2 re-attaches to the currently running #1. From a CI standpoint, it is not clear that #2 never actually successfully ran.
* If #1 is done, then #2 runs it own apply changes.

Since the former, can be disruptive, especially for selective apply changes, we are adding the options `--reattach` to `om apply-changes`. The current behaviour of auto-attachment will be removed. This provides more control and intention to a user.

This will be a breaking change in 4.0.
