### ISSUE TITLE
Add support for product syslog configuration 

### ISSUE THREAD

**Issue by dawu415** [pivotal-cf/om#331]
I am using PCF 2.4, APM v1.6.0 and Event Alert 1.2.6.

For some products such as PCF Metrics and Event Alerts, there is a syslog forwarding configuration tab in the tile.
<img width="706" alt="screen shot 2019-02-28 at 2 09 52 pm" src="https://user-images.githubusercontent.com/25437014/53596315-1a455d80-3b65-11e9-9ab6-cc6da999d40f.png">

These configurations do not seem to be able to be pulled down via `om staged-config` and also, they're not exposed in the tile's metadata file.   From reading the docs of opsmanager, there is an API that allows us to query and configure the syslog. http://docs.pivotal.io/pivotalcf/2-4/opsman-api/#retrieving-syslog-configuration-for-a-product

Would be good if this could be a feature of om

Other notes and findings. 

For some products, such as Event Alert,  it will return an error.
```om --env env/env.yml curl --path /api/v0/staged/products/p-event-alerts-e392615baa8e4ab67fe3/syslog_configuration
Status: 422 Unprocessable Entity
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Feb 2019 20:03:01 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: Ops Manager
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 9e8a05fb-b4bb-41f2-a628-4ef507145350
X-Runtime: 0.151686
X-Xss-Protection: 1; mode=block
{
  "errors": {
    "syslog_configuration": [
      "This product does not support the Ops Manager consistent syslog configuration feature. If the product supports custom syslog configuration, those properties can be set via the /api/v0/staged/products/:product_guid/properties endpoint.\n"
    ]
  }
}
```

For the PCF Metrics, it returns the configuration structure. 

```
om --env env/env.yml curl --path /api/v0/staged/products/apmPostgres-6c13e47296b28290416e/syslog_configuration
Status: 200 OK
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Feb 2019 20:16:56 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: Ops Manager
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 1ace8da6-cea3-417b-bfea-afee1999f4c0
X-Runtime: 0.147083
X-Xss-Protection: 1; mode=block
{
  "syslog_configuration": {
    "enabled": false,
    "address": null,
    "port": null,
    "transport_protocol": "tcp",
    "tls_enabled": false,
    "ssl_ca_certificate": null,
    "permitted_peer": null,
    "queue_size": null
  }
}
```

**Comment by kcboyle** [comment]
@dawu415 

A couple questions: 

1) Can you confirm the issue you are having? I am interpreting it as "I want to be able to configure syslog for certain tiles, but `om` will not return or set these configurations if I provide them". Is this is accurate summary of the feature you want? 

2)Can you clarify something for us? You said that both APM and Event Alerts have this configuration available, but only the metrics tile returns a non-error structure. 

    2a) If `om` were to utilize the `/api/v0/staged/products/product-type1-guid/syslog_configuration` endpoint, it would only be able to return the data that the endpoint _could_ return (thus, it would not return `syslog_configuratiion` for the Event Alerts tile, in your example above.) Is this desired behavior, or is there something else we could do to bridge the gap?

**Comment by dawu415** [comment]
@kcboyle 
1. Yes that is right
2. From my current tests with only those two tiles,  that is right.
3. It seems like a tile bug and probably needs a talk with the tile authors.  The om cli could return an error to advise the user of whatever message that was returned from opsman.   At the same time, I am looking through and seeing if I can get some answers about that message from `event alerts`.

**Comment by kcboyle** [comment]
Hello again! To draft a proposal for this feature (PR welcome), let's include the following:
As a user of `om`, I would like to pull down and configure the `syslog_configuration` properties of tiles where these properties exist.
* `configure-product` needs to configure the `syslog_configuration` properties (only if they exist) for a desired tile 
* `staged-config` should pull down the `syslog_configuration` if the properties exist in Ops Manager. The format should match the currently existing format of other properties (a nested block underneath a dash-separated key)

Questions: 
* what is the desired behavior if a user provides a `syslog_configuration` for a tile that does not have a `syslog_configuration`? Should the command fail, or silently succeed ("nothing to do")?
* Which versions of OpsManager support the new `/api/v0/staged/products/product-type1-guid/syslog_configuration` endpoint? 
    * assuming a minimum supported version of OpsManager:
        * `configure-product` should only attempt to configure `syslog_configuration` IF the minimally supported version of Ops Manager or later
        * `staged-product` should not include a `syslog_configuration` on any tile that does not support it, OR is not on the minimally supported version of OpsManager or later.


could @anEXPer @jtarchie @jpmcb review this proposal and add to it/modify if necessary?

**Comment by jpmcb** [comment]
* If the user provides some `syslog_configuration` that is not supported, it would be beneficial to have a feedback loop. I don't think that it should fail outright, but a warning saying that the provided endpoint dose not support this configuration. It could also say the `syslog_confiiguration` needs to be set manually via the OpsMan guid. 
* I agree that `configure-product` and `staged-product` should only attempt this given a minimal version of OpsManager. Are we able to confirm which version of OpsManager this api endpoint is supported in? 
* If the user provides `syslog_configuration` for `configure-product` on an unsupported opsman, should we:  
    1. fail fast and prompt the user to remove the section from the configuration? 
    2. Provide a warning stating that `syslog_configuration` is not supported but continue to configure the other properties? 
    3. Or continue without prompt as there is `nothing to do` for that configuration? 
    
    Providing some kind of feedback loop as a warning would enable automation to continue but hopefully allow the user to refactor their configurations. 

Otherwise, the proposal looks great!

**Comment by taotao20082006** [comment]
My customer is running on `PCF: 2.4.9, APM: 1.6.0-build.41` hits similiar issue. He is not able to pull down apmPostgres syslog configurations when running the `om staged-config --product-name=apmPostgres` command. This issue prevents him to put in the exact properties selector field names such as `.properties.syslog_selector.enabled.port` for the apmPostgres tile pipeline configuration.  

May I know if anyone have any idea from om perspective about these properties selector names for ampPostgres tile as customer found those names are not identical for other configurations (rabbitMQ, MySQL, etc...) . for example: `.properties.syslog_migration_selector:` in mysql.yml while `.properties.syslog_selector:` in rabbitMQ.yml…Thanks.

**Comment by kcboyle** [comment]
Hi @taotao20082006 ! thanks for agreeing with this issue. 

We do have this prioritized, but will still, likely, not get to it within the next few weeks. This issue was created so that we could add support for setting syslog configuration in your `product-config.yml`. 

This is a known gap for PCF Metrics and Event Alerts, and we are happy to accept a PR if this is blocking your customer. 

From dawu415, the results of the `/api/v0/staged/products/apmPostgres-6c13e47296b28290416e/syslog_configuration` from above should be set like so in your `product-config.yml`:
```
product-name: <product>
product-properties: 
  <properties...>
resource-config:
  <resource-config...>
syslog-config:
  enabled: false
  transport_protocol: tcp
  tls_enabled: false
```
null values would not be included in `staged-config`, but you could set them if you had need of doing so (when this feature is completed).


are you seeing something inconsistent from the `/api/v0/staged/products/GUID/properties` endpoint that you see from rabbitMQ and apmPostgres? `.properties.syslog_migration_selector:` seems like a property that would be nested under the `product-properties` section, not in the `syslog-config` section (even if it looks like that's where it should be).
If it is an issue with what is returned in `product-properties`, there is not a lot `om` can do to fix it, as we are doing a straight pull-down/pass-through of config GET/PUT to Ops Manager.

**Comment by taotao20082006** [comment]
Hi @kcboyle, 

Thanks for your update!

**Comment by iplay88keys** [comment]
@dawu415 @taotao20082006 This has been added and will be in 3.2.0! Closing this issue as a result. Commits tagged with [#167173691]
