### ISSUE TITLE
om incorrectly reports an error when an ops manager verifier triggers a warning

### ISSUE THREAD

**Issue by Logiraptor** [pivotal-cf/om#335]
We are using ops manager in an environment which requires special IAAS configuration. Because of this, some Ops Manager verifiers fail. We have disabled those verifiers, and they now simply report a warning in the UI, and a 207 (multi-status) in the API. `om` incorrectly reports that as an error and stops configuring the director.

Here is the error we get on `configure-director`:

```
$ om -e combine-env.yml configure-director --config director-template.yml --vars-file om-vars.yml
started configuring director options for bosh tile
finished configuring director options for bosh tile
started configuring availability zone options for bosh tile
successfully fetched AZs, continuing
could not execute "configure-director": availability zones configuration could not be applied: request failed: unexpected response:
HTTP/1.1 207 
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 22:20:50 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: Ops Manager
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 64df4a71-9ef7-4c93-876a-38a01550426b
X-Runtime: 62.353585
X-Xss-Protection: 1; mode=block

ec
{"verifications":{"warnings":{"base":["Availability zone(s) were saved but there are verification errors which may prevent you from deploying","Could not log in: Connection failed: execution expired, type: AvailabilityZonesVerifier"]}}}
0

```

You can see that the HTTP status is 207, and the body includes a warning about the AvailabilityZonesVerifier.

I believe one way to fix this would be to change the line [here](https://github.com/pivotal-cf/om/blob/f6abe8a489aa9c85bcbbe7d2e54735eeb46fce62/api/validation.go#L12) to instead check that Status is <= 299 and >= 200. 

I'm happy to prepare a PR if that would be helpful.

**Comment by kcboyle** [comment]
Thanks for opening an issue! We've been discussing this internally for a while, but wanted to give some OS visibility to some of the main points. 
1) The `/api/v0/staged/director/availability_zones` endpoint is a newer endpoint and the OpsMan team has been making efforts to be more descriptive with what they tell users. The 207 is meant to tell people: "the information you entered was valid, but it caused the Ops Manager verifiers to fail, and apply changes will likely fail too".
2) We don't want to just accept the 207 as just "passed but warning" because `Verifier changes could be solved external or they could indicate a typo in a credential. Essentially they are warnings that are meant to tell an operator that Apply Changes will probably fail because of some issue that needs resolution. In a few cases, the operator knows better and would like to disable a verifier, which they can do via the API  in order to unblock themselves to trigger Apply Changes.`

A solution for this, as this issue is from a newer endpoint that should match parity with the older way of doing things (see @Logiraptor 's [gist](https://gist.github.com/Logiraptor/1f717aaf2af465c9cd7e162b72b96286) for other examples), is to add an _opt-in_ flag to skip these configuration verifiers for `configure-product` and `configure-director`.

The description should mention that this flag is not recommended for production use, and should be used for testing purposes only, and should be disabled by default.

**Comment by Logiraptor** [comment]
@kcboyle I've made an initial commit which gives the desired behavior, but after reading your response again, I'm realizing that it's more appropriate to scope the flag to just `configure-product` and `configure-director`. I'll work on making that change. Once I get the thumbs up on implementation, I will work on updating the docs with an appropriate warning.

**Comment by kcboyle** [comment]
Cool. Let us know when you feel good about it @Logiraptor , and we'll take a look at the PR

**Comment by Logiraptor** [comment]
@kcboyle After talking with the team here, we think it's actually better to keep this as implemented on that branch (a global flag). The reason is that OM will be migrating towards 207 as a general means to signal verifier warnings, so making it a per-command flag will potentially make us have to add support reactively as they migrate the api.

Do you mind taking a look at the code and giving feedback?

**Comment by kcboyle** [comment]
Addressed via merged PR: https://github.com/pivotal-cf/om/pull/338
