### ISSUE TITLE
Selective apply-changes may consistently cause issues

### ISSUE THREAD

**Issue by brightzheng100** [pivotal-cf/om#363]
When trying selective `apply-changes` with errand control by specifying `-p` and `-c`, it may (or may not) cause issues -- some situation it's happy to go through; but once it raises this issue, it will always have this issue.

Command like:
```
$ om version
0.54.0
$ om -e env.yaml apply-changes -p <PRODUCT_NAME> -c <PRODUCT_NAME>-errand.yml
```

> Note: OpsMan is on v2.3.x

Error message:
```
The product with guid "<PRODUCT_NAME>-<UUID>" cannot be found in deployed products. Has the product been deployed
```

I realised that if we staged more than one products but wanted to selectively apply changes for anyone, it would definitely encounter this issue.

But the worse case was, even I had one tile staged and wanted to apply changes for it, it may (or may not) cause this issue as well.

**Comment by kcboyle** [comment]
@brightzheng100 

There are multiple issues around selective deploy already #325, and an undocumented issue around trying a selective deploy where a bosh link had changed (bosh will not detect what deployments need to be redeployed when a bosh link changes. you, as the user are responsible for know when to update a dependent deployment).

Could you potentially give us a workflow that will consistently replicate this issue so that we can explore this? 

Another question, does this happen on tiles that are already deployed, but just need to be selectively applied (think an update to a stemcell, so you would disable certain errands for that run with `-c`), or is this a brand new Ops Manager that has deployed neither product?

**Comment by kcboyle** [comment]
@brightzheng100 

A kindly reminder to give a little more context on the above please.

**Comment by brightzheng100** [comment]
FYI @kcboyle. 
It may be caused by some scenarios, based on my experiments:
1. new tile deployment -- this is exactly what I reported here;
2. upgrade tile which has dependency (e.g. to PAS) triggered floating stemcell

**Comment by kcboyle** [comment]
@brightzheng100 

Thank you for the context. We must have missed where you mentioned it was a new tile before.

Can you elaborate a little more on (2)? We're a little confused as to what exactly is happening. It sounds like you have 2 tiles deployed already, let's say PAS and Healthwatch for simplicity. 
You want to upgrade the stemcell for Healthwatch selectively, but because HW is dependent on PAS, selective apply changes also deploys PAS _as well_ as HW? 
Can you clarify that our interpretation of that issue is correct?

To go back to your issue on (1), we tested this using OpsMan 2.6 (which is coming out soon) and we didn't appear to have any problems. Our environment has PAS, Healthwatch, and PAS-Windows deployed. We decided to add the Event Alerts tile. Our steps were:
- upload tile to ops manager
- stage tile
- configure tile
- upload stemcell
- create a config file that has the errands present (for our test, we ran `staged-config`, deleted all but the errands section, and changed the value of one of the errands to always run)
- run om -e env.yaml apply-changes -p p-event-alerts -c p-event-alerts-errands.yml
Result:
`om` ran apply changes only for p-event-alerts, and did not run anything for PAS. 

Can you give an example of what tile pairs are not working for you in 2.3?

**Comment by kcboyle** [comment]
@brightzheng100 wanted to follow up with you on this issue, as it appears to have been awhile since our last follow up

**Comment by kcboyle** [comment]
@brightzheng100 we're still confused as to why this is causing issues. From everything that we have tested, there is no problem. Can you please give us an example of what tile pairs are not working, and/or describe your process a little more?

**Comment by brightzheng100** [comment]
The cases I found when I was working with a customer include:
1. we staged more tiles, say RMQ, MySQL, and wanted to apply changes for only one tile, say MySQL;
2. (then we applied changes altogether manually) and carried on the next new tile deployment (forgot which one already, maybe Redis), it failed again as what I reported here (which was not yet deployed  of course as it's a new one)

FYI @kcboyle

**Comment by kcboyle** [comment]
@brightzheng100 

Can you go through the same procedure in the UI, and confirm a few things for us? 
1) stage and configure all of your tiles
2) in the UI, apply changes to only one of those tiles(include disabling errands)
3) in the UI, apply changes to the other tile(include disabling errands)

do you get the same errors?

**Comment by kcboyle** [comment]
@brightzheng100  could you follow up on this for us? thanks!

**Comment by kcboyle** [comment]
@brightzheng100 another reminder to update on this issue please!

**Comment by brightzheng100** [comment]
I'm closing this issue as I don't use selective apply-changes any more.

**Comment by aegershman** [comment]
Using full “apply changes” for every change is unfeasible for us. We’ve used selective-deploy with lots of success in all our environments. If you (or anyone?) feel compelled to share what problems happened, that’d be great, because now I’m wondering if there are “gotcha”’s lurking that I’m not aware of.

**Comment by kcboyle** [comment]
We'd be very interested in this as well. We are aware of many, such as we (and OpsMan) cannot guarantee success if tiles are selectively deployed in an incorrect order (an update to healthwatch that relies on a change in PAS for instance), but if anyone can expand on some of these "gotchas", we'd like to make it as reliable as we can

**Comment by brightzheng100** [comment]
I believe two major things we can focus on to make it `production-grade`:

1. The dependency mechanism and (auto) detection. This is to embed something that we can rely on without the need to trail-and-fail;

2. The function consistency between backend APIs and the `om` cli. I heard others mentioned that using APIs may work better or simply `om curl`, which I haven't heavily tried but it might be a good reminder.

**Comment by aegershman** [comment]
Hm maybe I don't fully understand the original problem that happened?

The dependency mechanism makes sense, though I  think that's something outside the scope of what `om` can do since it would either require metadata to be declared & packaged w/ the `*.pivotal` tile, or a feature that'd need to be baked into BOSH + bosh manifests itself, probably? I don't know.

Personally haven't had any problems with `om apply-changes -p xyz -c abc` on a single product while other products/stemcells are staged for changes. We're on opsmgr 2.6.x though so maybe that's the delta?

thoughts?

**Comment by kcboyle** [comment]
@brightzheng100 to address #1, what do you mean my auto-detection?
We are interpreting it as "detect what tiles I have made changes to, and only do a selective apply on those products". Am I interpreting correctly? I can expand on why we have decided not to have `om` support that process. If it is only for dependencies, I would agree with @aegershman's assessment. There are other tools that deal with dependency management and detection (such as the upgrade planner tool). _**what workflow would you expect for "dependency mechanism and (auto) detection" if we included it in `om`?**_

To address #2, what commands are people saying are better just using `om curl`? om is not a strict 1->1 mapping for the ops manager API (that's why om curl exists). if there are workflows that would require multiple `om curl` calls and some kind of transformation in between, we are happy to take a feature request to make that process easier. 
Otherwise, `om` is intended to bridge common API calls (`configure-product`, for example, makes calls to 1-6 different ops manager endpoints) to make the process easier for the user. Other commands, such as `pending-changes`, are meant to display the information received from the API in a way that is easier to read as a user, as well as offering a fail state that can provide a blocker in automation. 

**_Can you explain what you mean by "function consistency"? what are people wanting `om` to have that we do not provide?_** As said earlier, we're open to discussion and pull requests, but we can't talk about vague things we do not know about.
