### ISSUE TITLE
config-template should support no version flag

### ISSUE THREAD

**Issue by ramonskie** [pivotal-cf/om#391]
in the tile-config-generator there was a flag named `--do-not-include-product-version`
this would result in a flat directory structure without the tile version subdirectory

**Comment by jpmcb** [comment]
Hi @ramonskie! Thanks for this issue. 

We have several stories around the `config-template` command. Initially, the logic from tile-config-generator was moved into `om config-template` as an experimental first pass (note that the command has `**EXPERIMENTAL**` in the help description). We plan to bring more features into this command from tile-config-generator and refine it's usage.

We will look at including this flag so that users can experience a flat file structure.

**Comment by jtarchie** [comment]
We were selective in the features we brought over. To limit the things that needed to be supported.

Is this a feature you required to do your work?

**Comment by nbconklin** [comment]
Thanks for sharing - we have some upcoming work to make improvements to the config-template. Would like to circle back with you when we've done that - happy to hear more context from you in the meantime. Thank you.

**Comment by ramonskie** [comment]
we have build ci that automatically upgrade cf tiles and because this is all standardized.
thats why we use 1 directory for each tile. so a versioned directory makes things way more complicated.

please let me know when the upcoming improvements are done so i can do some more tests.

**Comment by kcboyle** [comment]
@ramonskie we have not made a new release of `om` yet, but there are commits on master that have most of the changes we have made recently to `config-template`. 

A summary of the original issue to assist in a PR if you'd like to create one:
Adding a flag for do not include version essentially would allow removing version from file structure so that their pipelines can map to a general product rather than mapping to the version of that product.
  - This removes the ability to track diffs unless you are using git.
  - This could be considered a workflow optimization and/or an advanced feature.

What we would expect from a PR:
- the addition of a new flag for `config-template`, named something like `--exclude-version bool ADVANCED: excludes the version from the resulting file structure.`
- proper testing for this feature (there is a lack of unit tests for `config-template` currently. We expect that any new features be properly unit and/or integration tested. If you're feeling extra saucy, we'd love help backfilling these unit tests)
- proper documentation in the CHANGELOG for the work.

**Comment by jghiloni** [comment]
I'll take a look at this

**Comment by jghiloni** [comment]
As for the backfill of unit tests, i'll consider that in another PR 😉
