### ISSUE TITLE
om config-template should support tiles with replicator. 

### ISSUE THREAD

**Issue by calebwashburn** [pivotal-cf/om#413]
Some tiles support being replicated (ie - https://network.pivotal.io/products/p-isolation-segment/).  This is a process that modifies the tile metadata which config-template needs to be able to support to generate templates.  Since om config-template only supports pulling the metadata directly from pivnet not from a tile that has been replicated this isn't possible.  Adding support to also take a `.pivotal` file would allow config-template to be used on replicated tiles as well.

**Comment by kcboyle** [comment]
To rephrase, this is a request to allow `config-template` to take in a tile either from pivnet(current) or from a local .pivotal tile. 

This solves the following issues:
- `config-template` cannot be used with isolation segment tiles, because the replication happens _after_ the pivnet download.
- (inferred) `config-template` cannot be used by teams doing local tile development, because their tiles in development are not on pivnet. 

Does this sound correct? 

Happy to accept a PR, but this will likely take a bit to get prioritized. 
I'd like to see a couple test cases for this as well:
- existing behavior unbroken
- new behavior added
- validation failure if product provided is not a pivotal tile (I believe we check this elsewhere in `om`)

**Comment by KeepAustinWired** [comment]
We added the ability to use a local tile for `config-template`. It will be out in a future release.
