### ISSUE TITLE
`configure-ldap-authentication` should support the `--vars/-file` pattern

### ISSUE THREAD

**Issue by jpluscplusm** [pivotal-cf/om#426]
Some of the information required by `configure-ldap-authentication` is secret, and enforcing a "no secrets in config files" approach is made harder by the command not supporting the `--vars-file` pattern.

Without this support, we (@florentflament and myself) found ourselves having to fall back to process substitution with `bosh interpolate`. Whilst this works, it adds unnecessary complexity.

Given that other `om` commands support vars (e.g. `configure-director`), we would like to request this feature be added to `configure-ldap-authentication` and similar auth-/bootstrap-related commands :-)

**Comment by kcboyle** [comment]
Hi @jpluscplusm ! 

We understand that the command requires secrets. `configure-authentication`, `configure-saml-authentication`, and `configure-ldap-authentication` all take the values you can set as command line (or config file) arguments. 

_technically_, the `--config` file for `configure-*-authentication` is a payload the command uses like `configure-director`. This is different from the `--env` file (or the global arguments that you can set via env var) because of this. `configure-*-authentication` functionally works the same as `configure-director` or `configure-product`, because it is not a command that is used consistently (like the global vars), but a configuration that is run only once. 

It is reasonable to assume that the only reason you can set the individual values for `configure-authentication` is because this page has not changed during upgrades of Ops Manager, and thus did not necessitate the need for constant updates to the code to accommodate those changes, and thus did not necessitate the need to force the user to create the required json payload for configuring authentication (this was the process and the use case for migrating the former `configure-bosh` command into `configure-director`). We are not keen on allowing the values for setting authentication to be set via env var because it is used for configuration purposes, not for authentication with the environment purposes.

Because configuration is subject to change at the whim of an ops manager on any release, we generally do not like to tie ourselves down to the names of those configurations with something like an env var (the command line variables are likely only still around because they do not change often).

Do you have a list of other auth/bootstrap related commands we could look into?

**Comment by kcboyle** [comment]
These features have been added in om release [4.2.0](https://github.com/pivotal-cf/om/blob/master/CHANGELOG.md#420). Closing this issue.
