### ISSUE TITLE
Uploaded Stemcell couldn't be listed out in OpsMan's Stemcell Library

### ISSUE THREAD

**Issue by brightzheng100** [pivotal-cf/om#427]
I only installed one tile which was PAS `v2.4.9`, with Stemcell `v170.133`.

Now I wanted to downgrade my Stemcell to `v170.120`, which is also within the applicable stemcell range of `170.78–170.133`.

So I upload-stemcell:

```
om --env env/dev/env/env.yml upload-stemcell --floating=true --stemcell /tmp/build/2a19969b/stemcell/light-bosh-stemcell-170.120-google-kvm-ubuntu-xenial-go_agent.tgz ''
processing stemcell
beginning stemcell upload to Ops Manager
 20.78 KiB / 20.78 KiB [============================================] 100.00% 0s

finished upload
```

But I couldn't see it listed in OpsMan's Stemcell Library so I had no way to select it to apply.

There was a workaround though: I un-staged PAS tile, apply changes, and then I staged PAS tile again...and both stemcells of `v170.120` and `v170.133` were listed there.
I could select any of them for apply-changes.

So there must be some inconsistency issue for how to list the applicable stemcells for a tile.

**Comment by ssapra** [comment]
Hi @brightzheng100, after a stemcell is assigned to a product, it's not possible to downgrade the stemcell. By unstaging the product, and restaging it, you have another opportunity to pick the desired stemcell. Since there are multiple valid stemcells that could be assigned, OpsManager does not auto-assign it, so that's why you are able to pick v170.120.

**Comment by jtarchie** [comment]
@brightzheng100, was this a feature request or a perceived bug? We got the OpsManager to clarify above about it.

**Comment by brightzheng100** [comment]
In fact, we did that once in one production env to downgrade the stemcell for PAS `v2.5.8` from `v250.106` to `v250.99` which was successful.
So I believe it's still 100% doable. @ssapra 

While thinking whether it's a feature request or bug, I'd consider it's a logic defect. @jtarchie 

The current logic that I'm guessing, without looking at any code, might be something like:

For a given tile, it lists only the stemcells that fulfill below criteria:
1. currently **assigned stemcell** to the tile, in my case it's `v170.133`;
2. other stemcells with **higher version** than currently assigned stemcell;
3. other lower version stemcells already assigned to other tiles but are still within the applicable stemcell range

That explains my case, when I have only one PAS tile, all stemcells lower than `v170.133` would look like disappeared even after a successful upload, as the logic would just ignore them.

Now my suggestion is:

1. If there is a stemcell uploaded before the clean-up at the end of apply-changes, it should be listed out if it's in the tile's stemcell range for further assignment;

2. It's okay to clear them up after apply-changes as they could be considered "no use".

**Comment by kcboyle** [comment]
@brightzheng100 , if ops manager does not allow for the downgrade of a stemcell, or if downgrade is non-supported bug behavior on the Ops Manager side, having `om` support it seems like an impossibility (or at the least a bad idea)

Were you only able to downgrade _before_ you apply-changes, or after? 

Why do you want to do a downgrade?

**Comment by brightzheng100** [comment]
There was an `S1` case which was caused by Stemcell and downgrading Stemcell was the only choice; by default the `download-product` task in Platform Automation will retrieve the latest applicable Stemcell within the range, say by given `250.22-250.106`, the Stemcell versioned at `250.106` would be downloaded, assigned and applied -- that's the motivation.

**Comment by kcboyle** [comment]
@brightzheng100 if you need an earlier stemcell, you can use `download-product` with the stemcell slug. Especially if this is a one-time thing, that might be the better way to do it rather than change `download-product` to take a version of a stemcell to download. 

`upload-stemcell` also supports `--floating=false`, which will not auto-associate a stemcell in your environment when you upload it, so you can choose which products to associate it with. 

The use case you described seems like you are having an issue with `download-product`, but your original issue seems like you have an issue with not being able to see the stemcell in the UI (which we cannot help).

If you are using `upload-stemcell --floating=false`, you can use this in parallel with `assign-stemcell` to assign it to a product in your Ops Manager. Did this workflow not work for you? Even after your use case explanation, I'm having a hard time understanding what your actual problem was.

**Comment by kcboyle** [comment]
Back to your original ask, Ops Manager does not support a downgrade, and `om` cannot do something that Ops Manager will not let us do. I'm going to close this issue.
