### ISSUE TITLE
Prompt For Password If Not Provided

### ISSUE THREAD

**Issue by timlharrison** [pivotal-cf/om#442]
I would like the OM CLI to prompt me for my admin password if it is not provided on the command line to prevent the password from appearing in shell history.

**Comment by kcboyle** [comment]
Hi @timlharrison ! 

There are many ways that we already allow you to pass passwords to the command so that they are not in the shell history.

From native bash: 
- if you put a space in front of the command, it will not save the command in the history

Using `om`:
- you can set your password using environment variables (password for basic authentication is called `OM_PASSWORD` for instance). You can find the full list of ENV-able values by running `om -h`
- many commands support `--vars-file` flag. passwords can be stored in the vars files and passed in to the commands that way.
- if this is a global password (`om --password` for example), you can put every command line argument you would like to in an `--env` file.
    Example:
    ```bash
    om --username user --password pass --target example.com
    ```
    can become 
    ```bash
    om --env env.yml
    ```
    where env.yml looks something like:
    ```yaml
    # env.yml
    username: user
    password: pass
    target: example.com
    ```

Do any of these solutions work for you?

**Comment by timlharrison** [comment]
I can make it work using these solutions, but ideally it would work the same as the CF CLI.

**Comment by kcboyle** [comment]
The reason why it cannot work that way is that Ops Manager can be configured using basic authentication _or_ LDAP/SAML. These authentication methods require different arguments.
LDAP/SAML require `--client-secret` and `--client-id`, while basic auth requires `--username` and `--password`. We can't tell what kind of authentication is required from the API, we just pass what you give us along and hope it works.

**Comment by kcboyle** [comment]
I am going to close this issue for now, but feel free to continue to comment on this channel, or maybe reach out to Pivotal Support to request a feature in the Ops Manager API that could make this possible.

**Comment by timlharrison** [comment]
I didn't realize this was an OpsMan API shortcoming... thanks for pointing that out.
