### ISSUE TITLE
om bosh-env should be able to independently set credhub and bosh vars

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#458]
See #385 for more context

A nice to have feature for `bosh-env` would be to allow bosh and credhub vars to be set separately. A use case for this would be if a user needed to interact with bosh using a credhub that was not deployed via bosh (or vice versa). Right now, this would require the user to manually unset the credhub vars and/or reset the existing credhub vars that they desired. 

We shouldn't break the existing behavior of `bosh-env`, so when running `om bosh-env`, it should, by default, include credhub and bosh env vars. 

The following is a first pass as to how this could look. It is open to discussion
To exclude credhub vars
```bash
om bosh-env --exclude-credhub
```

To exclude bosh vars
```bash
om bosh-env --exclude-bosh
```

I would expect that these could be used together, but nothing would be set if both flags were passed (perhaps with a message saying "nothing to do"), but it is also understandable that passing both flags would produce an error.

Thank you for the proposal @aegershman!

**Comment by iplay88keys** [comment]
@kcboyle I'd be happy to pick this up and submit a PR for it if you all are ok with that.

**Comment by iplay88keys** [comment]
I'm thinking of doing something similar to the products command where passing no values sets both BOSH and credhub by default and you can pass either a `--bosh/-b` or `--credhub/-c`. As such, you could pass both flags if you want everything, but it would be the same as passing no flags. Also, there wouldn't need to be an error message, which would be easy to miss anyways due to the common use with `eval`.

**Comment by kcboyle** [comment]
That sounds a lot more consistent than the original proposal. I like your proposed implementation. Happy to accept a PR if you work on it.
