### ISSUE TITLE
a command to display available, staged, and deployed products alongside each other

### ISSUE THREAD

**Issue by eitansuez** [pivotal-cf/om#466]
as a platform engineer, i'd like a command that gives me a combined view of available, staged, and deployed products.

something along these lines:

<img width="1083" alt="om_products" src="https://user-images.githubusercontent.com/1054937/74500945-32b1a380-4eae-11ea-9ed5-7a940f04dc79.png">

i just forked this repo today and started working on an implementation in a branch named `products-command`.

would love your feedback.  let me know if that's something that'd be worth incorporating as an additional om subcommand.

**Comment by eitansuez** [comment]
anybody here? ;-)

**Comment by eitansuez** [comment]
other than cf-gitbot of course

**Comment by jtarchie** [comment]
Sorry, we monitor the github repo, but don't always respond quickl, because our backlog surface area is beyond here at the moment.

We currently have individual commands for each of the `available`, `staged`, and `deployed` states.
Why is seeing them altogether useful to the operator?
How does this help in automation?

**Comment by eitansuez** [comment]
i basically found myself invoking all three individual commands for the sake of comparing available, staged, and deployed versions  (aside: each of the commands (available-products, staged-products, and deployed-products) will not necessarily produce a list of the same ordering).  so i found myself wanting to see all this information side by side.  which led me to looking into building this combined command.  i would be curious to know if anyone else who uses om would find this command useful.  sounds like so far i'm the only one. :-)

**Comment by kcboyle** [comment]
I think what I would prefer to see (rather than just a new command) is a combined command that has flags to show each of the three separately, and defaults to showing the combined view. 

Implementation _shouldn't_ initially delete the original commands, but I would really like to see them deprecated and removed in the next major bump of `om`. (We have an example of changes made for deprecation in the `tile-metadata` command -- ie, renaming the new method to include 'deprecated', editing the description, etc)

`om products` should return a table like the screenshot above.

`om products --available` should return a table almost identical to `om available-products`:
Note: for consistency, consider changing `VERSION` column to `AVAILABLE`
```
+----------------------+----------------+
|         NAME         |    AVAILABLE   |
+----------------------+----------------+
| pas-windows          | 2.8.0          |
| cf                   | 2.8.0          |
| p-healthwatch        | 1.8.0-build.66 |
| pivotal-telemetry-om | 1.0.0-build.2  |
+----------------------+----------------+
```

And follow the same pattern for `om products --staged`, and `om products --deployed`

**Comment by eitansuez** [comment]
i like it.

**Comment by eitansuez** [comment]
i had coded an implementation around the time i posted this issue in a fork here: https://github.com/eitansuez/om/commits/products-command
but it does not incorporate the ideas in kira's comments above (from feb 20).
but perhaps it can serve as a starting point.

**Comment by iplay88keys** [comment]
@eitansuez I'm thinking of digging into this in my free time to see if I can come up with a clean solution taking into account Kira's comment from above. @kcboyle Does that work for you all?

**Comment by eitansuez** [comment]
that'd be great.  my fork has a branch named "products-command" with the commits from my initial go: https://github.com/eitansuez/om/tree/products-command

**Comment by iplay88keys** [comment]
Added the first pass of this PR!

**Comment by iplay88keys** [comment]
@eitansuez I ended up writing my implementation from scratch, so let me know if you see any missing edge cases that you covered in your implementation.

**Comment by eitansuez** [comment]
thanks.  i don't think there was anything special in my implementation other than exposing the command that produced the screenshot, attempting to follow conventions and trying to reuse as much of the existing codebase that was in place.

**Comment by kcboyle** [comment]
PR was accepted and should come out in the next release of `om`

**Comment by eitansuez** [comment]
awesome.  thank you so much!
