### ISSUE TITLE
OM 2.9 introduces "Recreate the BOSH Director" feature

### ISSUE THREAD

**Issue by klakin-pivotal** [pivotal-cf/om#468]
Two things:

1) Ops Manager 2.9 has introduced a "Recreate the BOSH Director VM" parameter. This parameter is a boolean called `bosh_director_recreate_on_next_deploy`. It is used just like the existing `bosh_recreate_on_next_deploy` parameter. FWIW the story that introduced this change is here: https://www.pivotaltracker.com/story/show/170879932

2) The prose that describes the `bosh_recreate_on_next_deploy` option should be updated to emphasize the fact that this option typically only re-creates BOSH-deployed VMs and does not touch the Director.

cc: @ystros @mingxiao

**Comment by kcboyle** [comment]
Proposal: 
Edit to the `apply-changes --recreate-vms` behavior to include the bosh director during the recreate (so that the command is honest). To keep the command consistent with other apply-changes flags:

`om apply-changes --recreate-vms --product-name {product}` should recreate the vms for that product

`om apply-changes --recreate-vms --skip-deploy-products` should recreate only the BOSH director vms

`om apply-changes --recreate-vms` should recreate all product vms, _and_ the BOSH director vm.

Would recommend doing something similar for this as we did for `--recreate-vms`: [update the properties in the bosh director](https://github.com/pivotal-cf/om/blob/master/commands/apply_changes.go#L132-L136) for a single run. This will likely require some refactoring of logic to accommodate the differing use cases. Also, keep these new features fully tested in both [`apply-changes.go`](https://github.com/pivotal-cf/om/blob/master/commands/apply_changes.go) and [`director_service.go`](https://github.com/pivotal-cf/om/blob/master/api/director_service.go)

**Comment by xyloman** [comment]
At first pass this looks really good to me.  @aegershman and myself have been anticipating these capabilities for a while very exciting to see it come to pass.

**Comment by kcboyle** [comment]
this will be included in `om` 4.7.0
