### ISSUE TITLE
om configure-director creates a new default config in some cases

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#469]
**Description**
There have been multiple reports of a second "Default" config showing up for some customers when configuring the director.

This is most likely due to the fact that there is a`POST` and a `PUT` endpoint for `/api/v0/staged/director/iaas_configurations`. One of them will overwrite all and the other will just add/modify.

It seems likely that the guid for the `PUT` is not the same as the existing guid and it creates a new config as a result.

**Additional Dev Info**
Most likely here: https://github.com/pivotal-cf/om/blob/336568aebd499cb1e62253afc6d720b392e49f36/api/director_service.go#L316-L355

This is a problem because you can have an unexpected deploy of the bosh director without any actual changes

**Comment by iplay88keys** [comment]
We have determined that there is an initial "default" iaas_configuration returned by the `/api/v0/staged/director/iaas_configurations` endpoint and this initial "default" iaas_config remains even after another one has been explicitly configured.

We don't see this in our own pipelines because we use "default" as the name of our iaas_config. Users will tend to do the same to if they use our `staged-director-config` workflow as the name will be filled in already unless they explicitly decide to change it.
