### ISSUE TITLE
"om" limits number of service broker plans to 10

### ISSUE THREAD

**Issue by shahramk** [pivotal-cf/om#473]
A customer is using `om` to automate their New Relic service broker installation. they are using ~100 New Relic sub-accounts and they need to add around 100 plans to the service broker. Apparently om limits the number of plans to 10. Here is the url to [om/configtemplate/generator/product_properties.go](https://github.com/pivotal-cf/om/blob/master/configtemplate/generator/product_properties.go#L227). It runs a loop of 10 to generate options files for up to 10 plans. Customer would like this limit to be removed.

Recommendation:
1 - provide option to pass the number of plans as a command line argument. If none is passed default to 10.
2 - or at least raise the limit to a larger number.

thank you

**Comment by jtarchie** [comment]
The number isn't a _limit_ it is merely just a number chosen for amount of things to generate.
This is affects all collections, not just service plans.

They are can copy and paste more operations into an opsfile to support more service plans at the moment.

1. We need a way for the user to discover what the property name is, so that the limit can be passed in for that property. 
2. Larger number is subjective here. For your customer this would make sense, for other customers we could get, "there's too many service plans generated now."

I think (1) would be the best move. We'd be happy to discuss the interface and accept a PR on it.

**Comment by kcboyle** [comment]
Adding the enhancement label. For this issue, `config-template` should take an _optional_ parameter that can allow for more than the _default_ 10 that it generates now

**Comment by kcboyle** [comment]
this will be included in `om` 4.7.0
