### ISSUE TITLE
pending changes returns exit status 1 for a new director install

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#496]
when installing a director for the first time, if you run `om pending-changes --check` it will return a non-zero exit status code, though the status is `install` instead of `changed`

`install` should be a valid success state.

**Comment by jtarchie** [comment]
While investing `pending-changes`, we noticed there was another related issue.
Whether we did a `--check` or not, the completeness check will fail (when incomplete).
This was not the intended behaviour.

With the above change (https://github.com/pivotal-cf/om/commit/57b81d23b0ee075a8dcc9bed144408984d2e7f32),
we made it so `--check` is the only reason an `exit 1` can occur -- other than standard connection issues.

Since `--check` allows a by-pass, we no longer have to explicitly check for the `install` state.
