### ISSUE TITLE
OM tool does not support S3 V4 signature

### ISSUE THREAD

**Issue by pakiheart** [pivotal-cf/om#59]
When you enable S3 in director tile and select V4 signature, region field is required.  The tool does not update the field causing the settings to fail to save.
![image](https://cloud.githubusercontent.com/assets/12705327/24725526/e5e29e40-1a14-11e7-938c-6e5eb4ee86c5.png)

**Comment by davewalter** [comment]
Hi @pakiheart,

Are you including a region in your request? If not, you will run into an issue we just discovered where the Ops Manager will respond with a `200 OK` code which tells `om` that it successfully saved the settings but in fact, nothing was saved because a required field was missing.

If this is not the case, could you please provide a sample payload (without credentials) and response.

Regards,
Dave

**Comment by davewalter** [comment]
Hi @pakiheart,

Just checking in to see if you had found the issue with your configuration so that we could close this issue?

Regards,
Dave

**Comment by madamkiwi** [comment]
Hi Rehan,

Here's an example director-configuration that configures S3 with the V4 signature:

```json
{
  "ntp_servers_string": "us.pool.ntp.org, time.google.com",
  "blobstore_type": "s3",
  "s3_blobstore_options": {
    "endpoint": "https://s3.amazonaws.com/",
    "bucket_name": "some-bucket",
    "access_key": "some-key",
    "secret_key": "some-secret",
    "signature_version": "4",
    "region": "us-west-1"
  }
}
``` 

We are going to close this issue, but please re-open if this doesn't work for you.

Thanks,

K && Andrew
