### ISSUE TITLE
skipping network configuration during configure-bosh option

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/om#81]
I can an only configure iaas and director options.
The other options result in the following error, and are ignored: 
`skipping network configuration: detected deployed director - cannot modify network`

it appears that lines 95-100 are absolute, when it should only be for a specific option, and result in the rest of the options not being test for.

**Comment by zachgersh** [comment]
@DonBower - if you already have a bosh director deployed we are intentionally stopping you from reconfiguring the network due to the fact that the Ops Manager throws an error when you attempt to do this.

If you want to be able to reconfigure the bosh director network you have to uninstall the director tile.

**Comment by DonBower** [comment]
@zachgersh I believe this is a self imposed restriction.
There are lots of changes I can make via the GUI, that OM has blocked.
Just one example, Add a new Network.

**Comment by davewalter** [comment]
Hi @DonBower,

We don't currently use the Ops Manager API to configure the director, so I think this check was put in place to attempt to protect the user. We are going to investigate switching to an API endpoint for this soon so we will revisit the need for this fast-fail at that time.

Regards,
Dave
