### ISSUE TITLE
Feature Request: Add deploy-errands flag to apply-changes command

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/om#92]
According to the documentation, [Triggering an install process](http://opsman-dev-api-docs.cfapps.io/#triggering-an-install-process),  we can set which errands to run during an apply changes.
This is very useful, especially when making changes to something other that ERT.

Although the implementation of the **/api/v0/installations** endpoint varies between 1.9 and 1.11, it would be nice to be able to at least say, "apply changes and run these errands too..." as most, if not all, of our post-deploy errands are disabled.

**Comment by DonBower** [comment]
Here is how we may be able to implement:
We could form the json string similar to below, and the tool would substitute the product-name for the product-guid:

```
{
  "enabled_errands": {
    "<product-name, i.e. cf>": {
      "post_deploy_errands": [
        "smoke-tests",
        "push-apps-manager",
        "notifications",
        "notifications-ui",
        "push-pivotal-account",
        "autoscaling",
        "autoscaling-register-broker"
      ]
    }
  }
}
```

**Comment by kenchenpcf** [comment]
@DonBower Is this a feature that is still useful?

**Comment by DonBower** [comment]
We use om in pipielines to kick off apply-changes.
To be able to specify which errands to run at the same time would be beneficial, because today, we use a curl command to start the apply with the desired errands, which returns immediately, and then we call om again with the apply command to “attach” to the current apply to make the pipeline synchronous.

**Comment by mcwumbly** [comment]
We spec'd this out in [this tracker story](https://www.pivotaltracker.com/n/projects/2145041/stories/155641251), but would happily accept a PR if someone wants to pick it up sooner.

---

As a om user, I want to specify the errands to run post deploy and pre delete, so that I can customize the errands when applying changes.

`om apply-changes --errands` or `om apply-changes -e`

This mirrors the functionality in the Ops Man API described here: http://opsman-dev-api-docs.cfapps.io/#triggering-an-install-process

om apply-changes --errands-config /some/errands/config.yml

/some/errands/config.yml
```
---
product1_name:
  pre-delete:
    errand_a: true
    errand_b: false
  post-deploy:
    errand_c: "default"
product2_name:
  post-deploy:
    errand_a: false
  pre-delete:
    errand_b: "when-changed"
```

The post deploy and pre delete errand states should mirror the Ops Man API options.

See related github request here: https://github.com/pivotal-cf/om/issues/92

**Acceptance:**
Given that I run `om apply-changes`,
When I specify errands to run via the `errands` argument,
Then I see that the specified errands are enabled/disabled post-deploy or pre-delete.

**Comment by jtarchie** [comment]
The comment specifies values for the `pre-delete` and `post-deploy` that don't match up directly to the values for the API payload expected.
The docs for the OpsMan API specify `run_pre_delete` and `run_post_deploy`.
Do you want them to match, or have that transformation?

**Comment by mcwumbly** [comment]
I updated those keys to match the API. One thing that doesn't match is we're using product names rather than GUIDs. I think that is desirable.

**Comment by fredwangwang** [comment]
In discussion with @jtarchie we are moving forward with creating a PR for this story, that will be forwards compatible with eventual selective deploy implementation in `om`

We will create an _optional_ config file for the apply changes command.

```YAML
product-name1:
  deploy: true
  errands:
    run_pre_delete:
      errand_a: true
      errand_b: false
    run_post_deploy:
      errand_c: "default"
product-name2:
  deploy: true
```

If there are 2 products installed `product-name1`, `product-name2`, and `product-name3` this configuration will deploy all three products, and use the errand configuration for `2` and `3` and defined in the tile. `1` will run the errands as defined in the config file. 

If something is not defined in the file, assume the default.
